In [2]:
list = [5,10,15,20]
list

[5, 10, 15, 20]

In [4]:
list2 = [1,"apple",4.5]
list2

[1, 'apple', 4.5]

In [6]:
tuple = (1,2,3)
tuple

(1, 2, 3)

In [8]:
tuple[1] = 10

TypeError: 'tuple' object does not support item assignment

In [10]:
dict = {"No.1":"apple", "No.2":"orange", "No.3":"banana"}
dict

{'No.1': 'apple', 'No.2': 'orange', 'No.3': 'banana'}

In [12]:
#NumPyをimport
import numpy as np

In [14]:
#リストの作成（一次元）
data = [1,2,3,4]
#array関数でndarray配列にする
a = np.array(data)
a

array([1, 2, 3, 4])

In [18]:
#1リストが1行になる
data2 = ([1,2,3,4],
         [5,6,7,8],
         [9,10,11,12])
#array関数で行列にする
b = np.array(data2)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
#１次元配列（ベクトル）
zeros = np.zeros(10) 
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
zeros2 = np.zeros((4,5))
zeros2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
#全ての要素が1のベクトルを作る
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
#全ての要素が1の行列を作る
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.full(5,3)

array([3, 3, 3, 3, 3])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#arange(終わりの数字)
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
#arange(始める数字, 終わりの数字)
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [36]:
#arange(始める数字, 終わりの数字, 間の数字)
np.arange(5,50,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [38]:
#行列にする
np.arange(5,50,3).reshape(5,3)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38],
       [41, 44, 47]])

In [40]:
#ndarray配列の形状を調べる
a.shape

(4,)

In [42]:
np.shape(a)

(4,)

In [44]:
#行列の形状もわかる
b.shape

(3, 4)

In [46]:
#次元を確認する
a.ndim

1

In [48]:
#行列は2次元
b.ndim

2

In [50]:
#引数に指定する方法でも使える
np.ndim(a)

1